apiVersion: v1
kind: Deployment
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  replicas: 1
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
