apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  namespace: default
  labels:
    app: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: gcr.io/milkin-finance/hello-node:v1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: default
spec:
  selector:
    app: hello-node
  ports:
    - port: 3000        # port exposed by the service
      targetPort: 3000  # containerPort in the pod
  type: NodePort        # or LoadBalancer if your cluster supports it
